#:schema https://json.schemastore.org/rustfmt.json

comment_width                = 120
doc_comment_code_block_width = 120
edition                      = "2024"
format_code_in_doc_comments  = true
format_macro_bodies          = true
format_macro_matchers        = true
group_imports                = "StdExternalCrate"
hard_tabs                    = false
imports_granularity          = "Crate"
max_width                    = 120
normalize_comments           = true
normalize_doc_attributes     = true
reorder_impl_items           = true
reorder_imports              = true
reorder_modules              = true
style_edition                = "2024"
tab_spaces                   = 4
unstable_features            = true
use_small_heuristics         = "Off"
wrap_comments                = true
